name: auto-app2-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bwa
  - samtools
  - adapterremoval
  - gatk4
  - qualimap
  - pysam
  - requests
  - tqdm
  - pip
  - pip:
      - pathlib2 